# Base image
FROM python:3.10-slim

# Install system dependencies
RUN apt-get update && apt-get install -y \
libpq-dev \
gcc \
&& apt-get clean \
&& rm -rf /var/lib/apt/lists/*

# Copy requirements file and install Python libraries
COPY requirements.txt /app/requirements.txt
RUN pip install --no-cache-dir -r /app/requirements.txt

# Copy your project files into the container
COPY . /app

# Set the working directory
WORKDIR /app

# Run your main script
CMD ["python", "main.py"]
