version: '3.9'

services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    networks:
      - kubu-net

  frontend:
    build: ./frontend
    ports:
      - "8080:80"
    networks:
      - kubu-net

  nginx:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend
    networks:
      - kubu-net

networks:
  kubu-net:
    driver: bridge
