version: "3.9"

services:
  redis:
    image: redis:7
    restart: always
    ports:
      - "6379:6379"

  backend:
    build: ./backend
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - redis
    environment:
      - PYTHONUNBUFFERED=1

  celery_worker:
    build: ./backend
    command: ["./celery_worker_start.sh"]
    volumes:
      - ./backend:/app
    depends_on:
      - backend
      - redis
