# Example: secrets.toml

# OpenAI API key
OPENAI_API_KEY = "AIzaSyA-oZL7iczXS-_tD0fcnpm6zGCfF_jwEkQ"

# If you are using the API service provided by OpenAI, include the following line:
OPENAI_API_TYPE = "openai"

# If you are using the API service provided by Microsoft Azure, include the following lines:
OPENAI_API_TYPE = "azure"
AZURE_API_BASE = "your_azure_api_base_url"
AZURE_API_VERSION = "your_azure_api_version"

# You.com search API key
YDC_API_KEY = "AIzaSyA-oZL7iczXS-_tD0fcnpm6zGCfF_jwEkQ"

# Bing Search API key
BING_SEARCH_API_KEY = "your_bing_search_api_key"

# Database credentials
DB_HOST = "your_database_host"
DB_PORT = "your_database_port"
DB_USER = "your_database_user"
DB_PASSWORD = "your_database_password"
DB_NAME = "your_database_name"

# Add any other API keys or sensitive information here
