version: "3.8"

services:
  webapp:
    build: .
    command: uvicorn tests.fixtures.server:app --host 0.0.0.0 --port 8000
    expose:
      - 8000

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certs:/certs:ro
    ports:
      - "443:443"
    depends_on:
      - webapp
