name: AI Webapp CI/CD

on:
  push:
    branches:
      - main
      - dev
  pull_request:

env:
  REGISTRY: ghcr.io
  REPO: yourdockerrepo/ai-webapp
  KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - run: pip install -r backend/requirements.txt
      - run: pytest backend/tests --junitxml=reports/test-results.xml
      - uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: reports/test-results.xml

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push backend image
        run: |
          docker build -t $REGISTRY/$REPO/backend:${{ github.sha }} -f backend/Dockerfile .
          docker push $REGISTRY/$REPO/backend:${{ github.sha }}

  deploy_k8s:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Setup kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: v1.27.1
      - name: Setup Kubeconfig
        run: |
          echo "${{ env.KUBE_CONFIG_DATA }}" | base64 --decode > $HOME/.kube/config
      - name: Deploy Helm chart
        run: |
          helm upgrade --install ai-webapp ./helm-chart \
            --set backend.image=$REGISTRY/$REPO/backend:${{ github.sha }}
