name: Build, Sign, and Verify Docker Image

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: ghcr.io/web4application/kubu:main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -t $IMAGE_NAME .

      - name: Push Docker image
        run: |
          docker push $IMAGE_NAME

      - name: Install Cosign
        run: |
          COSIGN_VERSION="v2.1.1"
          curl -Lo cosign https://github.com/sigstore/cosign/releases/download/$COSIGN_VERSION/cosign-linux-amd64
          chmod +x cosign
          sudo mv cosign /usr/local/bin/

      - name: Sign Docker image
        env:
          COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSWORD }}
        run: |
          echo "$COSIGN_PASSWORD" | cosign sign --key cosign.key --password-stdin $IMAGE_NAME

      - name: Verify Docker image signature
        run: |
          cosign verify --key cosign.pub $IMAGE_NAME
