name: Test AI Webapp

on: [push, pull_request]

jobs:
  test-matrix:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        env: [dev, staging, production]
        python-version: [3.10]
    services:
      redis:
        image: redis
        ports: ['6379:6379']

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        pip install httpx pytest

    - name: Run FastAPI HTTP2 Test
      run: |
        uvicorn tests.fixtures.server:app --host 0.0.0.0 --port 8000 &
        sleep 2
        pytest tests/
